simplemooc/courses/urls.py
from django.conf.urls import url
from simplemooc.courses import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(
        r'^solicitar-curso/$',
        views.create_course_request,
        name='create_course_request'
    ),
    url(
        r'^cursos/trb/$',
        views.list_courses_trb,
        name='list_courses_trb'
    ),
    url(
        r'^cursos/normal/$',
        views.list_courses_normal,
        name='list_courses_normal'
    ),
    url(
        r'^curso/(?P<pk>\d+)/$',
        views.course,
        name='course'
    ),
    url(
        r'^curso/(?P<pk>\d+)/criar-licao/$',
        views.create_lesson,
        name='create_lesson'
    ),
    url(
        r'^curso/(?P<pk>\d+)/licao/(?P<lesson_pk>\d+)/$',
        views.view_lesson,
        name='view_lesson'
    ),
    url(
        r'^curso/(?P<pk>\d+)/editar-licao/(?P<lesson_pk>\d+)$',
        views.edit_lesson,
        name='edit_lesson'
    ),
    url(
        r'^curso/(?P<c_pk>\d+)/licao/(?P<l_pk>\d+)/add-material$',
        views.create_material_lesson,
        name='create_material_lesson'
    ),
    url(
        r'^curso-trb/(?P<pk>\d+)/$',
        views.course_trb,
        name='course_trb'
    ),
    url(
        r'^curso/(?P<pk>\d+)/criar-licao-trb/$',
        views.create_lesson_trb,
        name='create_lesson_trb'
    ),
    url(
        r'^curso/(?P<pk>\d+)/editar-licao-trb/(?P<lesson_pk>\d+)$',
        views.edit_lesson_trb,
        name='edit_lesson_trb'
    ),
    url(
        r'^curso/(?P<c_pk>\d+)/licao-trb/(?P<l_pk>\d+)/add-material$',
        views.create_material_lesson_trb,
        name='create_material_lesson_trb'
    ),
    url(
        r'^curso/(?P<pk>\d+)/licao-trb/(?P<lesson_pk>\d+)/$',
        views.view_lesson_trb,
        name='view_lesson_trb'
    ),
    url(
        r'^curso/(?P<pk>\d+)/lesson/(?P<lesson_pk>\d+)/nivel-conhecimento/$',
        views.add_knowledge_level,
        name='add_knowledge_level'
    ),
    url(
        r'^curso-trb/(?P<c_pk>\d+)/nivel-conhecimento/(?P<n_pk>\d+)/$',
        views.delete_knowledge_level,
        name='delete_knowledge_level'
    ),
    url(
        r'^curso-trb/(?P<course_pk>\d+)/lesson/(?P<lesson_pk>\d+)/add-descricao-verbo/(?P<cat_pk>\d+)/$',
        views.add_verb_description,
        name='add_verb_description'
    ),
    url(
        r'^curso-trb/(?P<c_pk>\d+)/editar-descricao/(?P<v_pk>\d+)/categoria/(?P<cat_pk>\d+)/$',
        views.edit_verb_description,
        name='edit_verb_description'
    ),
    url(
        r'^curso-trb/(?P<c_pk>\d+)/deletar-descricao/(?P<v_pk>\d+)/$',
        views.delete_verb_description,
        name='delete_verb_description'
    ),
    url(
        r'^curso-trb/(?P<c_pk>\d+)/lesson/(?P<l_pk>\d+)/add-categoria-processo-cognitivo/(?P<n_pk>\d+)$',
        views.add_category_cognitive,
        name='add_category_cognitive'
    ),
    url(
        r'^curso-trb/(?P<c_pk>\d+)/deletar-categoria-processo-cognitivo/(?P<cat_pk>\d+)$',
        views.delete_category_cognitive,
        name='delete_category_cognitive'
    ),
    url(
        r'^curso-trb/(?P<c_pk>\d+)/lesson/(?P<l_pk>\d+)/visualizar-tabela/$',
        views.get_trb_table,
        name='get_trb_table'
    ),
    url(
        r'^(?P<slug>[\w_-]+)/$',
        views.details,
        name='details'
    ),
    url(
        r'^(?P<slug>[\w_-]+)/inscricao/$',
        views.enrollment,
        name='enrollment'
    ),
    url(
        r'^(?P<slug>[\w_-]+)/cancelar-inscricao/$',
        views.undo_enrollment,
        name='undo_enrollment'
    ),
    url(
        r'^(?P<course_slug>[\w_-]+)/criar-anuncio/$',
        views.create_announcement,
        name='create_announcement'
    ),
    url(
        r'^(?P<course_slug>[\w_-]+)/listar-anuncios/$',
        views.list_announcements,
        name='list_announcements'
    ),
    url(
        r'^(?P<slug>[\w_-]+)/anuncios/$',
        views.announcements,
        name='announcements'
    ),
    url(
        r'^(?P<slug>[\w_-]+)/anuncios/(?P<pk>\d+)/$',
        views.show_announcement,
        name='show_announcement'
    ),
    url(
        r'^(?P<course_slug>[\w_-]+)/anuncios-curso/(?P<announcement_pk>\d+)/$',
        views.show_announcement_to_professor,
        name='show_announcement_to_professor'
    ),
    url(
        r'^(?P<slug>[\w_-]+)/aulas/$',
        views.lessons,
        name='lessons'
    ),
    url(
        r'^(?P<slug>[\w_-]+)/aulas/(?P<pk>\d+)/$',
        views.lesson,
        name='lesson'
    ),
    url(
        r'^(?P<course_slug>[\w_-]+)/professor/materiais/(?P<pk>\d+)/$',
        views.show_material_to_professor,
        name='show_material_to_professor'
    ),
    url(
        r'^(?P<slug>[\w_-]+)/materiais/(?P<pk>\d+)/$',
        views.material,
        name='material'
    ),
]

simplemooc/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^', include('simplemooc.core.urls', namespace='core')),
    url(r'^cursos/', include('simplemooc.courses.urls', namespace='courses')),
    url(r'^contas/', include(
        'simplemooc.accounts.urls', namespace='accounts')),
    url(r'^forum/', include('simplemooc.forum.urls', namespace='forum')),
    url(r'^admin/', include(admin.site.urls)),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

simplemooc/courses/views.py
from itertools import chain

from django.contrib import messages
from django.contrib.contenttypes.models import ContentType

from django.shortcuts import (
    render,
    get_object_or_404,
    redirect
)
from django.contrib.auth.decorators import login_required

from simplemooc.courses.models import (
    Announcement,
    CategoryCognitiveProcess,
    ChooseCategoryCognitiveProcess,
    ChooseKnowledgeLevel,
    Course,
    CourseTRB,
    Enrollment,
    KnowledgeLevel,
    Lesson,
    LessonTRB,
    Material,
    MaterialTRB,
    Verb,
)

from simplemooc.courses.forms import (
    AnnouncementForm,
    AssignKnowledgeLevelForm,
    ChooseCategoryCognitiveProcessForm,
    CategoryDCPForm,
    CommentForm,
    ContactCourse,
    CourseRequestForm,
    KnowledgeLevelForm,
    LessonTRBForm,
    LessonForm,
    VerbForm,
    VerbFormChoices,
    MaterialForm,
    MaterialTRBForm,
)

from .management.commands._categories import CATEGORIES
from .management.commands._levels import LEVELS

from .decorators import enrollment_required
from .utils import format_name, get_course_by_instance


def index(request):
    template_name = 'courses/index.html'
    courses = list(chain(Course.objects.all(), CourseTRB.objects.all()))
    return render(request, template_name, {'courses': courses})


@login_required
def list_courses_trb(request):
    user = request.user
    template_name = 'courses/list_courses.html'
    context = {}
    if user.is_professor:
        courses = user.professor.courses_coursetrb_courses.all()
    else:
        courses = CourseTRB.objects.all()
    context['courses'] = courses
    context['is_trb'] = True
    return render(request, template_name, context)


@login_required
def list_courses_normal(request):
    user = request.user
    template_name = 'courses/list_courses.html'
    context = {}
    if user.is_professor:
        courses = user.professor.courses_course_courses.all()
    else:
        courses = Course.objects.all()
    context['courses'] = courses
    context['is_trb'] = False
    return render(request, template_name, context)


@login_required
def course(request, pk):
    template_name = 'courses/course.html'
    context = {}
    course = get_object_or_404(Course, pk=pk)
    context['course'] = course
    return render(request, template_name, context)


@login_required
def course_trb(request, pk):
    template_name = 'courses/course.html'
    context = {}
    course = get_object_or_404(CourseTRB, pk=pk)
    context['course'] = course
    return render(request, template_name, context)


@login_required
def create_course_request(request):
    template_name = 'courses/create_course_request.html'
    context = {}

    if request.method == 'POST':
        form = CourseRequestForm(request.POST)
        if form.is_valid():
            course_request = form.save(commit=False)
            course_request.professor = request.user.professor
            course_request.save()
            context['is_valid'] = True
            form = CourseRequestForm()
    else:
        form = CourseRequestForm()

    context['form'] = form

    return render(request, template_name, context)


@login_required
def edit_course(request, pk):
    template_name = ''
    context = {}
    # course = get_object_or_404(Course, pk=pk)
    return render(request, template_name, context)


def details(request, slug):
    template_name = 'courses/detail.html'
    context = {}
    course = get_course_by_instance(slug, Course, CourseTRB)
    if request.method == 'POST':
        form = ContactCourse(request.POST)
        if form.is_valid():
            context['is_valid'] = True
            form.send_mail(course)
            form = ContactCourse()
    else:
        form = ContactCourse()
    context['course'] = course
    context['form'] = form
    return render(request, template_name, context)


@login_required
def create_lesson(request, pk):
    template_name = 'courses/create_lesson.html'
    context = {}
    course = get_object_or_404(Course, pk=pk)
    if request.method == 'POST':
        form = LessonForm(request.POST)
        if form.is_valid():
            lesson = form.save(commit=False)
            lesson.course = course
            lesson.save()
            return redirect('courses:course', pk=pk)
    else:
        form = LessonForm()
    context['form'] = form
    context['course'] = course
    return render(request, template_name, context)


@login_required
def view_lesson(request, pk, lesson_pk):
    context = {}
    template_name = 'courses/view_lesson.html'

    lesson = get_object_or_404(Lesson, pk=lesson_pk)
    course = get_object_or_404(Course, pk=pk)

    context['lesson'] = lesson
    context['course'] = course

    return render(request, template_name, context)


@login_required
def edit_lesson(request, pk, lesson_pk):
    template_name = 'courses/create_lesson.html'
    context = {}
    course = get_object_or_404(Course, pk=pk)
    lesson = get_object_or_404(Lesson, pk=lesson_pk)
    if request.method == 'POST':
        form = LessonForm(request.POST, instance=lesson)
        if form.is_valid():
            form.save()
            return redirect('courses:course', pk=pk)
    else:
        form = LessonForm(instance=lesson)
    context['form'] = form
    context['course'] = course
    return render(request, template_name, context)


@login_required
def create_material_lesson(request, c_pk, l_pk):
    template_name = 'courses/create_material.html'
    context = {}

    lesson = get_object_or_404(Lesson, pk=l_pk)

    if request.method == 'POST':
        form = MaterialForm(request.POST, request.FILES)
        if form.is_valid():
            material = form.save(commit=False)
            material.lesson = lesson
            material.save()
            return redirect('courses:view_lesson', pk=c_pk, lesson_pk=l_pk)
    else:
        form = MaterialForm()

    context['form'] = form
    context['lesson'] = lesson
    return render(request, template_name, context)


@login_required
def create_lesson_trb(request, pk):
    template_name = 'courses/create_lesson.html'
    context = {}
    course = get_object_or_404(CourseTRB, pk=pk)
    if request.method == 'POST':
        form = LessonTRBForm(request.POST)
        if form.is_valid():
            lesson = form.save(commit=False)
            lesson.course = course
            lesson.save()
            for level in form.cleaned_data.get('levels'):
                level = KnowledgeLevel.objects.create(
                    name=level.name,
                    description=level.description,
                    lesson=lesson
                )
            # import ipdb; ipdb.set_trace()
            return redirect('courses:course_trb', pk=pk)
    else:
        form = LessonTRBForm()
    context['form'] = form
    context['course'] = course
    context['levels'] = ChooseKnowledgeLevel.objects.all()
    return render(request, template_name, context)


@login_required
def edit_lesson_trb(request, pk, lesson_pk):
    template_name = 'courses/create_lesson.html'
    context = {}
    course = get_object_or_404(CourseTRB, pk=pk)
    lesson = get_object_or_404(LessonTRB, pk=lesson_pk)
    if request.method == 'POST':
        form = LessonTRBForm(request.POST)
        if form.is_valid():
            for level in form.cleaned_data.get('levels'):
                level.lessons.remove(lesson)
                level.lessons.add(lesson)
            # import ipdb; ipdb.set_trace()
            lesson.save()
            return redirect('courses:course_trb', pk=pk)
    else:
        form = LessonTRBForm(instance=lesson)
    context['form'] = form
    context['course'] = course
    return render(request, template_name, context)


@login_required
def view_lesson_trb(request, pk, lesson_pk):
    context = {}
    template_name = 'courses/view_lesson.html'

    lesson = get_object_or_404(LessonTRB, pk=lesson_pk)
    course = get_object_or_404(CourseTRB, pk=pk)

    context['lesson'] = lesson
    context['course'] = course

    return render(request, template_name, context)


@login_required
def create_material_lesson_trb(request, c_pk, l_pk):
    template_name = 'courses/create_material.html'
    context = {}

    lesson = get_object_or_404(LessonTRB, pk=l_pk)

    if request.method == 'POST':
        form = MaterialTRBForm(request.POST, request.FILES)
        if form.is_valid():
            material = form.save(commit=False)
            material.lesson = lesson
            material.save()
            return redirect('courses:view_lesson_trb', pk=c_pk, lesson_pk=l_pk)
    else:
        form = MaterialTRBForm()

    context['form'] = form
    context['lesson'] = lesson
    return render(request, template_name, context)


@login_required
def add_verb_description(request, course_pk, lesson_pk, cat_pk):
    template_name = 'courses/add_verb_description.html'
    context = {}

    course = get_object_or_404(CourseTRB, pk=course_pk)
    lesson = get_object_or_404(LessonTRB, pk=lesson_pk)
    category = get_object_or_404(CategoryCognitiveProcess, pk=cat_pk)
    name = category.name.lower()

    if request.method == 'POST':
        form = VerbForm(request.POST)
        if form.is_valid():
            verb = form.save(commit=False)
            verb.category_dimension = category
            verb.save()
            return redirect('courses:course_trb', pk=course.pk)
    else:
        form = VerbFormChoices(choices=Verb.VERBS[name])

    context['form'] = form
    context['course'] = course
    context['lesson'] = lesson
    context['category'] = category

    return render(request, template_name, context)


@login_required
def edit_verb_description(request, c_pk, v_pk, cat_pk):
    template_name = 'courses/add_verb_description.html'
    context = {}

    course = get_object_or_404(CourseTRB, pk=c_pk)
    verb = get_object_or_404(Verb, pk=v_pk)
    category = get_object_or_404(CategoryCognitiveProcess, pk=cat_pk)

    if request.method == 'POST':
        form = VerbForm(request.POST, instance=verb)

simplemooc/courses/templates/courses/add_category_cognitive.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="splash">
    <div class="pure-g-r">
        <div class="pure-u-1">
            <div class="l-box splash-text">
                <h1 class="splash-head">
                    {{ course.name }}
                </h1>
                <h2 class="splash-subhead">
                    {{ course.description }}
                </h2>
                <p>
                </p>
            </div>
        </div>
    </div>
</div>
<div class="pure-g-r content-ribbon" id="contato">
    <div class="pure-u-2-5">
        <h3>Cadastre mais um objetivo educacional para essa aula e nível</h3>
        {% if messages %}
            <p>
                Adicione outra abaixo ou volte para a <a href="{% url 'courses:course_trb' course.pk %}">página do curso</a>
            </p>
        {% endif %}
        <form class="pure-form pure-form-aligned" method="post">
        {% csrf_token %}
            <fieldset>
            {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
            {% endfor %}
                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Enviar</button>
                </div>
            </fieldset>
        </form>
    </div>
    <div class="pure-u-3-5 use-tips">
        <div class="l-box">
            <h4 class="content-subhead">TIPOS DE OBJETIVOS EDUCACIONAIS</h4>
        </div>
        <div class="l-box wrapper-content-info">
            <table>
                <tr>
                    {% for category in categories %}
                        <td>
                            <h4>{{ category }}</h4>
                            <a class="open" href="#" title="{{ category.description }}">ler descrição</a>
                        </td>
                    {% endfor %}
                </tr>
            </table>
        </div>
    </div>
</div>
{% endblock %}

simplemooc/courses/templates/courses/add_verb_description.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="splash">
    <div class="pure-g-r">
        <div class="pure-u-1">
            <div class="l-box splash-text">
                <h1 class="splash-head">
                    {{ course.name }}
                </h1>
                <h2 class="splash-subhead">
                    {{ course.description }}
                </h2>
                <p>
                </p>
            </div>
        </div>
    </div>
</div>
<div class="pure-g-r content-ribbon" id="contato">
    <div class="pure-u-2-3">
        <h4>O OBJETIVO EDUCACIONAL SERÁ ESCOLHIDO DE ACORDO COM O VERBO ABAIXO</h4>
        {% if is_valid %}
            <p>Seu formulário foi enviado com sucesso!</p>
        {% endif %}
        <form class="pure-form pure-form-aligned" method="post">
            {% csrf_token %}
            <fieldset>
                {% for field in form %}
                    <div class="pure-control-group">
                        {{ field.label_tag }}
                        {{ field }}
                        {{ field.errors }}
                    </div>
                {% endfor %}
                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Enviar</button>
                </div>
            </fieldset>
        </form>
    </div>
    <div class="pure-u-1-3 use-tips">
        <div class="l-box">
            <h4 class="content-subhead">OBJETIVOS EDUCACIONAIS JÁ INSERIDOS</h4>
        </div>
        <div class="l-box">
            <ul>
                {% for verb in category.verbs.all %}
                    <li>
                        <a href="#">{{ verb }}</a>
                        <ul>
                            <li>
                                {{ verb.educational_goal|truncatewords:"15" }}
                            </li>
                        </ul>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

simplemooc/courses/templates/courses/announcement_mail.html
{{ announcement.content|linebreaks }}

simplemooc/courses/templates/courses/announcements.html
{% extends "courses/course_dashboard.html" %}

{% block dashboard_content %}
	{% if user.is_professor %}
		<p>
			<a  class="pure-button pure-button-primary" href="{% url 'courses:create_announcement' course.slug %}">Criar anúncio</a>
		</p>
	{% endif %}
	{% for announcement in announcements %}
		<div class="well">
			<h2>
				{% if user.is_professor %}
					<a href="{% url 'courses:show_announcement_to_professor' course.slug announcement.pk %}">
						{{ announcement.title }}
					</a>
				{% else %}
					<a href="{% url 'courses:show_announcement' course.slug announcement.pk %}">
						{{ announcement.title }}
					</a>
				{% endif %}
			</h2>
			{{ announcement.content|linebreaks }}
			<p>
				<a href="{% url 'courses:show_announcement' course.slug announcement.pk %}#comments" title="">
				<i class="fa fa-comments-o"></i>
				{% with announcement.comments.count as comments_count %}
					{{ comments_count }} Comentário{{ comments_count|pluralize }}
				{% endwith %}
				</a>
			</p>
		</div>
	{% empty %}
		<h2>Sem anúncios</h2>
	{% endfor %}
	

{% endblock dashboard_content %}

simplemooc/courses/templates/courses/contact_email.html
<p><strong>Nome</strong>: {{ name }}</p>
<p><strong>Email</strong>: {{ email }}</p>
{{ message|linebreaks }}

simplemooc/courses/templates/courses/lesson.html
{% extends "courses/course_dashboard.html" %}

{% block breadcrumb %}
	{{ block.super }}
	<li>/</li>
	<li><a href="{% url 'courses:lessons' course.slug %}">Aulas</a></li>
	<li>/</li>
	<li><a href="{% url 'courses:lesson' course.slug lesson.pk %}">{{ lesson }}</a></li>
{% endblock breadcrumb %}

{% block dashboard_content %}
	<div class="well">
		<h2><a href="{% url 'courses:lesson' course.slug lesson.pk %}">{{ lesson }}</a></h2>
		{{ lesson.description|linebreaks }}
		<p>
			<h4>Material da Aula</h4>
			<table class="pure-table full">
				<thead>
					<tr>
						<th>
							Nome
						</th>
						<th>
							Ação
						</th>
					</tr>
				</thead>
				<tbody>
					{% for material in lesson.materiais.all %}
						<tr class="{% cycle '' 'pure-table-odd' %}">
							<td>
								{{ material }}
							</td>
							<td>
								{% if material.is_embedded %}
									{% if user.is_professor %}
										<a href="{% url 'courses:show_material_to_professor' course.slug material.pk %}">
											<i class"fa fa-video-camera"></i>
											Acessar
										</a>
									{% else %}
										<a href="{% url 'courses:material' course.slug material.pk %}">
											<i class"fa fa-video-camera"></i>
											Acessar
										</a>
									{% endif %}
								{% elif material.material_file %}
									<a href="{{ material.material_file.url }}">
										<i class"fa fa-download"></i>
										Baixar
									</a>
								{% else %}
									<p>Sem arquivos disponíveis até o momento.</p>
								{% endif %}
							</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</p>
	</div>
</div>
{% endblock dashboard_content %}

simplemooc/courses/templates/courses/lessons.html
{% extends "courses/course_dashboard.html" %}

{% block breadcrumb %}
	{{ block.super }}
	<li>/</li>
	<li><a href="{% url 'courses:lessons' course.slug %}">Aulas</a></li>
{% endblock breadcrumb %}

{% block dashboard_content %}
{% for lesson in lessons %}
	<div class="well">
	    <h2>
	    	<a href="{% url 'courses:lesson' course.slug lesson.pk %}">{{ lesson }}</a>
	    </h2>
	    <p>
	        {{ lesson.description|truncatewords:'20'}}
	        <br />
	        <a href="{% url 'courses:lesson' course.slug lesson.pk %}" title="">
		        <i class="fa fa-eye"></i>
		        Acessar Aula
	        </a>
	    </p>
	</div>
{% empty %}
	<div class="well">
	    <h2>
	        Nenhuma aula disponível.
	    </h2>
	</div>
{% endfor %}
{% endblock dashboard_content %}

simplemooc/courses/templates/courses/show_announcement.html
{% extends "courses/course_dashboard.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li><a href="">/</a></li>
    <li><a href="{% url 'courses:show_announcement' course.slug announcement.pk %}">{{ announcement }}</a></li>
{% endblock breadcrumb %}

{% block dashboard_content %}
<div class="well">
    <h2>{{ announcement.title }}</h2>
    {{ announcement.content|linebreaks }}
</div>
<div class="well">
    <h4 id="comments">Comentários
    <a class="fright" href="#add_comment">Comentar</a></h4>
    <hr />
    {% for comment in announcement.comments.all %}
        <p>
            <strong>{{ comment.user }}</strong> disse à {{ comment.created_at|timesince }} atrás: <br />
            {{ comment.comment|linebreaksbr }}
        </p>
    <hr />
    {% empty %}
        <p>
            Não há comentários
        </p>
    {% endfor %}
    <form method="post" class="pure-form pure-form-stacked" id="add_comment">
        {% csrf_token %}
        <fieldset>
            {{ form.non_field_errors}}
            {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
            {% endfor %}
            <div class="pure-controls">
                <button type="submit" class="pure-button pure-button-primary">Enviar</button>
            </div>
        </fieldset>
    </form>
</div>
{% endblock dashboard_content %}

simplemooc/courses/templates/courses/undo_enrollment.html
{% extends "courses/course_dashboard.html" %}

{% block dashboard_content %}
	<form action="" method="post">
		{% csrf_token %}
		<h3>Deseja realmente cancelar sua inscrição?</h3>
		<div class="pure-controls">
			<button type="submit" class="pure-button pure-button-primary">Confirmar</button>
			<a href="{% url 'courses:announcements' course.slug %}" class="pure-button pure-button">Cancelar</a>
		</div>
	</form>
{% endblock dashboard_content %}

simplemooc/courses/templates/courses/view_lesson.html
{% extends "courses/course_dashboard.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'courses:lessons' course.slug %}">Aulas</a></li>
    <li>/</li>
    <li><a href="{% url 'courses:lesson' course.slug lesson.pk %}">{{ lesson }}</a></li>
{% endblock breadcrumb %}

{% block dashboard_content %}
    <div class="well">
        <h2><a href="{% url 'courses:lesson' course.slug lesson.pk %}">{{ lesson }}</a></h2>
        {{ lesson.description|linebreaks }}
        <p>
            <h4>Material da Aula</h4>
            <table class="pure-table full">
                <thead>
                    <tr>
                        <th>
                            Nome
                        </th>
                        <th>
                            Ação
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for material in lesson.materiais.all %}
                        <tr class="{% cycle '' 'pure-table-odd' %}">
                            <td>
                                {{ material }}
                            </td>
                            <td>
                                {% if material.is_embedded %}
                                    <a href="{% url 'courses:show_material_to_professor' course.slug material.pk %}">
                                        <i class"fa fa-video-camera"></i>
                                        Acessar
                                    </a>
                                {% elif material.material_file %}
                                    <a href="{{ material.material_file.url }}">
                                        <i class"fa fa-download"></i>
                                        Baixar
                                    </a>
                                {% else %}
                                    <p>Sem arquivos disponíveis até o momento.</p>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </p>
        <p>Adicionar material</p>
        {% if course.is_normal_course %}
            <a href="{% url 'courses:create_material_lesson' course.pk lesson.pk %}" class="pure-button">Adicionar</a>
        {% else %}
            <a href="{% url 'courses:create_material_lesson_trb' course.pk lesson.pk %}" class="pure-button">Adicionar</a>
        {% endif %}
    </div>
</div>
{% endblock dashboard_content %}