simplemooc/accounts/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns(
    '',
    url(r'^$', 'simplemooc.accounts.views.dashboard', name='dashboard'),

    url(
        r'^entrar/$',
        'django.contrib.auth.views.login',
        {'template_name': 'accounts/login.html'},
        name='login'
    ),

    url(
        r'^sair/$',
        'django.contrib.auth.views.logout',
        {'next_page': 'core:home'},
        name='logout'
    ),

    url(
        r'^cadastre-se/$',
        'simplemooc.accounts.views.register',
        name='register'
        ),

    url(
        r'^nova-senha/$',
        'simplemooc.accounts.views.password_reset',
        name='password_reset'
        ),

    url(
        r'^confirmar-nova-senha/(?P<key>\w+)/$',
        'simplemooc.accounts.views.password_reset_confirm',
        name='password_reset_confirm'
        ),

    url(r'^editar/$', 'simplemooc.accounts.views.edit', name='edit'),

    url(r'^editar-senha/$',
        'simplemooc.accounts.views.edit_password',
        name='edit_password'
        ),
)

simplemooc/courses/urls.py
from django.conf.urls import url
from simplemooc.courses import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(
        r'^solicitar-curso/$',
        views.create_course_request,
        name='create_course_request'
    ),
    url(
        r'^cursos/trb/$',
        views.list_courses_trb,
        name='list_courses_trb'
    ),
    url(
        r'^cursos/normal/$',
        views.list_courses_normal,
        name='list_courses_normal'
    ),
    url(
        r'^curso/(?P<pk>\d+)/$',
        views.course,
        name='course'
    ),
    url(
        r'^curso/(?P<pk>\d+)/criar-licao/$',
        views.create_lesson,
        name='create_lesson'
    ),
    url(
        r'^curso/(?P<pk>\d+)/licao/(?P<lesson_pk>\d+)/$',
        views.view_lesson,
        name='view_lesson'
    ),
    url(
        r'^curso/(?P<pk>\d+)/editar-licao/(?P<lesson_pk>\d+)$',
        views.edit_lesson,
        name='edit_lesson'
    ),
    url(
        r'^curso/(?P<c_pk>\d+)/licao/(?P<l_pk>\d+)/add-material$',
        views.create_material_lesson,
        name='create_material_lesson'
    ),
    url(
        r'^curso-trb/(?P<pk>\d+)/$',
        views.course_trb,
        name='course_trb'
    ),
    url(
        r'^curso/(?P<pk>\d+)/criar-licao-trb/$',
        views.create_lesson_trb,
        name='create_lesson_trb'
    ),
    url(
        r'^curso/(?P<pk>\d+)/editar-licao-trb/(?P<lesson_pk>\d+)$',
        views.edit_lesson_trb,
        name='edit_lesson_trb'
    ),
    url(
        r'^curso/(?P<c_pk>\d+)/licao-trb/(?P<l_pk>\d+)/add-material$',
        views.create_material_lesson_trb,
        name='create_material_lesson_trb'
    ),
    url(
        r'^curso/(?P<pk>\d+)/licao-trb/(?P<lesson_pk>\d+)/$',
        views.view_lesson_trb,
        name='view_lesson_trb'
    ),
    url(
        r'^curso/(?P<pk>\d+)/lesson/(?P<lesson_pk>\d+)/nivel-conhecimento/$',
        views.add_knowledge_level,
        name='add_knowledge_level'
    ),
    url(
        r'^curso-trb/(?P<c_pk>\d+)/nivel-conhecimento/(?P<n_pk>\d+)/$',
        views.delete_knowledge_level,
        name='delete_knowledge_level'
    ),
    url(
        r'^curso-trb/(?P<course_pk>\d+)/lesson/(?P<lesson_pk>\d+)/add-descricao-verbo/(?P<cat_pk>\d+)/$',
        views.add_verb_description,
        name='add_verb_description'
    ),
    url(
        r'^curso-trb/(?P<c_pk>\d+)/editar-descricao/(?P<v_pk>\d+)/categoria/(?P<cat_pk>\d+)/$',
        views.edit_verb_description,
        name='edit_verb_description'
    ),
    url(
        r'^curso-trb/(?P<c_pk>\d+)/deletar-descricao/(?P<v_pk>\d+)/$',
        views.delete_verb_description,
        name='delete_verb_description'
    ),
    url(
        r'^curso-trb/(?P<c_pk>\d+)/lesson/(?P<l_pk>\d+)/add-categoria-processo-cognitivo/(?P<n_pk>\d+)$',
        views.add_category_cognitive,
        name='add_category_cognitive'
    ),
    url(
        r'^curso-trb/(?P<c_pk>\d+)/deletar-categoria-processo-cognitivo/(?P<cat_pk>\d+)$',
        views.delete_category_cognitive,
        name='delete_category_cognitive'
    ),
    url(
        r'^curso-trb/(?P<c_pk>\d+)/lesson/(?P<l_pk>\d+)/visualizar-tabela/$',
        views.get_trb_table,
        name='get_trb_table'
    ),
    url(
        r'^(?P<slug>[\w_-]+)/$',
        views.details,
        name='details'
    ),
    url(
        r'^(?P<slug>[\w_-]+)/inscricao/$',
        views.enrollment,
        name='enrollment'
    ),
    url(
        r'^(?P<slug>[\w_-]+)/cancelar-inscricao/$',
        views.undo_enrollment,
        name='undo_enrollment'
    ),
    url(
        r'^(?P<course_slug>[\w_-]+)/criar-anuncio/$',
        views.create_announcement,
        name='create_announcement'
    ),
    url(
        r'^(?P<course_slug>[\w_-]+)/listar-anuncios/$',
        views.list_announcements,
        name='list_announcements'
    ),
    url(
        r'^(?P<slug>[\w_-]+)/anuncios/$',
        views.announcements,
        name='announcements'
    ),
    url(
        r'^(?P<slug>[\w_-]+)/anuncios/(?P<pk>\d+)/$',
        views.show_announcement,
        name='show_announcement'
    ),
    url(
        r'^(?P<course_slug>[\w_-]+)/anuncios-curso/(?P<announcement_pk>\d+)/$',
        views.show_announcement_to_professor,
        name='show_announcement_to_professor'
    ),
    url(
        r'^(?P<slug>[\w_-]+)/aulas/$',
        views.lessons,
        name='lessons'
    ),
    url(
        r'^(?P<slug>[\w_-]+)/aulas/(?P<pk>\d+)/$',
        views.lesson,
        name='lesson'
    ),
    url(
        r'^(?P<course_slug>[\w_-]+)/professor/materiais/(?P<pk>\d+)/$',
        views.show_material_to_professor,
        name='show_material_to_professor'
    ),
    url(
        r'^(?P<slug>[\w_-]+)/materiais/(?P<pk>\d+)/$',
        views.material,
        name='material'
    ),
]

simplemooc/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^', include('simplemooc.core.urls', namespace='core')),
    url(r'^cursos/', include('simplemooc.courses.urls', namespace='courses')),
    url(r'^contas/', include(
        'simplemooc.accounts.urls', namespace='accounts')),
    url(r'^forum/', include('simplemooc.forum.urls', namespace='forum')),
    url(r'^admin/', include(admin.site.urls)),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

simplemooc/accounts/models.py
from django.db import models
from django.contrib.auth.models import (
    AbstractBaseUser,
    PermissionsMixin,
    UserManager
)
from django.core import validators
from django.conf import settings
import re


class User(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(
        'Nome de Usuário',
        max_length=30,
        unique=True,
        validators=[
            validators.RegexValidator(
                re.compile('^[\w.@+-]+$'),
                'O nome de usuário só pode conter letras, números e @/./+/-/_',
                'invalid'
            )
        ]
    )
    email = models.EmailField(
        'E-mail',
        unique=True
    )
    name = models.CharField(
        'Nome',
        max_length=100,
        blank=True
    )
    is_active = models.BooleanField(
        'Está ativo?',
        blank=True,
        default=True
    )
    is_staff = models.BooleanField(
        'É da equipe?',
        blank=True,
        default=False
    )
    date_joined = models.DateTimeField(
        'Data de entrada',
        auto_now_add=True
    )

    objects = UserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def __str__(self):
        if self.is_professor:
            return 'Professor {} '.format(self.name or self.username)
        return self.name or self.username

    def get_short_name(self):
        return self.username

    def get_full_name(self):
        return str(self)

    @property
    def is_professor(self):
        return hasattr(self, 'professor')

    class Meta:
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'


class Professor(User):

    def __str__(self):
        return 'Professor - {}'.format(self.name or self.username)

    class Meta:
        verbose_name = 'professor'
        verbose_name_plural = 'professores'


class PasswordReset(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name='Usuário para recuperação de senha',
        related_name='resets'
    )
    key = models.CharField(
        'Chave',
        max_length=100,
        unique=True,
    )
    created_at = models.DateTimeField(
        'Criado em', auto_now_add=True
    )
    confirmed = models.BooleanField(
        'Confirmado?',
        default=False,
        blank=True
    )

    def __str__(self):
        return '{0} em {1}'.format(self.user, self.created_at)

    class Meta:
        verbose_name = 'Nova senha'
        verbose_name_plural = 'Novas senhas'
        ordering = ['-created_at']

simplemooc/accounts/forms.py
from django import forms
# from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from simplemooc.core.utils import generate_hash_key
from simplemooc.core.mail import send_mail_template
from simplemooc.accounts.models import PasswordReset, Professor


User = get_user_model()


class PasswordResetForm(forms.Form):

    email = forms.EmailField(label='Email')

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            return email
        raise forms.ValidationError('Email não cadastrado.')

    def save(self):
        user = User.objects.get(email=self.cleaned_data['email'])
        key = generate_hash_key(user.username)
        reset = PasswordReset(key=key, user=user)
        reset.save()
        template_name = 'accounts/password_reset_mail.html'
        subject = 'Criar nova senha no Simple MOOC'
        context = {
            'reset': reset
        }
        send_mail_template(subject, template_name, context, [user.email])


class RegisterForm(forms.ModelForm):

    is_professor = forms.BooleanField(
        label='Você é professor?',
        initial=False,
        required=False
    )
    password1 = forms.CharField(
        label='Senha',
        widget=forms.PasswordInput
    )
    password2 = forms.CharField(
        label='Confirmação de senha',
        widget=forms.PasswordInput
    )

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('Confirmação de senha incorreta.')
        return password2

    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user

    class Meta:
        model = User
        fields = ['username', 'email', 'is_professor']


class RegisterProfessorForm(RegisterForm):

    class Meta(RegisterForm.Meta):
        model = Professor


class EditAccountForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['username', 'email', 'name']

simplemooc/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
# from django.conf import settings
from django.contrib.auth import authenticate, login, get_user_model
from django.contrib.auth.forms import PasswordChangeForm, SetPasswordForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .forms import (
    RegisterForm,
    EditAccountForm,
    PasswordResetForm,
    RegisterProfessorForm
)
from .models import PasswordReset


User = get_user_model()


def register(request):
    template_name = 'accounts/register.html'
    if request.method == 'POST':
        is_professor = request.POST.get('is_professor', '')
        if is_professor:
            form = RegisterProfessorForm(request.POST)
        else:
            form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            user = authenticate(
                username=user.username,
                password=form.cleaned_data['password1']
            )
            login(request, user)
            return redirect('core:home')
    else:
        form = RegisterForm()
    context = {
        'form': form
    }
    return render(request, template_name, context)


@login_required
def dashboard(request):
    template_name = 'accounts/dashboard.html'
    return render(request, template_name)


def password_reset(request):
    template_name = 'accounts/password_reset.html'
    context = {}
    form = PasswordResetForm(request.POST or None)
    if form.is_valid():
        form.save()
        context['success'] = True
    context['form'] = form
    return render(request, template_name, context)


def password_reset_confirm(request, key):
    template_name = 'accounts/password_reset_confirm.html'
    context = {}
    reset = get_object_or_404(PasswordReset, key=key)
    form = SetPasswordForm(user=reset.user, data=request.POST or None)
    if form.is_valid():
        form.save()
        context['success'] = True
    context['form'] = form
    return render(request, template_name, context)


@login_required
def edit(request):
    context = {}
    template_name = 'accounts/edit.html'
    if request.method == 'POST':
        form = EditAccountForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Dados alterados com sucesso!')
    else:
        form = EditAccountForm(instance=request.user)
    context['form'] = form
    return render(request, template_name, context)


@login_required
def edit_password(request):
    template_name = 'accounts/edit_password.html'
    context = {}
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            context['success'] = True
    else:
        form = PasswordChangeForm(user=request.user)
    context['form'] = form
    return render(request, template_name, context)

simplemooc/accounts/templates/accounts/dashboard.html
{% extends "base.html" %}

{% load courses_tags %}

{% block content %}
{% load_my_courses user as enrollments %}
<div class="pure-g-r content-ribbon">
	<div class="pure-u-1">
		<ul class="breadcrumb">
		{% block breadcrumb %}
			<li><a href="{% url 'accounts:dashboard' %}">Meu Painel</a></li>
		{% endblock breadcrumb %}
		</ul>
	</div>
	<div class="pure-u-1-3">
		<div class="pure-menu pure-menu-open">
			<ul>
				{% with is_professor=user.is_professor  %}
					<li class="pure-menu-heading">
						{% if is_professor %}
							Bem vindo, Professor {{ user }}
						{% else %}
							Bem vindo, {{ user }}
						{% endif %}
					</li>
					{% block menu_options %}
						<li class="pure-menu-heading">Meus cursos</li>
						{% if is_professor %}
							<li>
								<a href="{% url 'courses:list_courses_normal' %}">
									Meus Cursos
								</a>
							</li>
							<li>
								<a href="{% url 'courses:list_courses_trb' %}">
									Meus Cursos utilizando Ferramenta Pedagógica de Apoio
								</a>
							</li>
							<li>
								<a href="{% url 'courses:create_course_request' %}">
									Enviar solicitação de criação de curso
								</a>
							</li>
						{% else %}
							{% for enrollment in enrollments %}
								<li>
									<a href="{% url 'courses:announcements' enrollment.course.slug %}">
										<i class="fa fa-book"></i>
										{{ enrollment.course }}
									</a>
								</li>
							{% empty %}
								<li>Nenhum curso encontrado</li>
							{% endfor %}
						{% endif %}
						<li class="pure-menu-heading">Conta</li>
						<li>
							<a href="{% url 'accounts:edit' %}">
								<i class="fa fa-cog"></i>
								Editar Informações
							</a>
						</li>
						<li>
							<a href="{% url 'accounts:edit_password' %}">
								<i class="fa fa-lock"></i>
								Editar Senha
							</a>
						</li>
					{% endblock menu_options %}
				{% endwith %}
			</ul>
		</div>
	</div>
	<div class="pure-u-2-3">
		<div class="inner">
		<div class="inner">
			{% block dashboard_content %}
				<h2>Meus Cursos</h2>
				{% with is_professor=user.is_professor %}				    
					{% if is_professor %}
						<p>Use a dashboard lateral para acessar seus cursos.</p>
					{% else %}
						{% for enrollment in enrollments %}				
						<div class="well">
							<h3>
								{{ enrollment.course }}
								({{ enrollment.course.start_date|date:'d/m/Y'|default:'Sem data'}})
							</h3>
							<p>
								{{ enrollment.course.description|linebreaks }}
							</p>
							<div class="pure-controls">
								<a href="{% url 'courses:announcements' enrollment.course.slug %}" class="pure-button pure-button-primary">Acessar</a>
								<a href="{% url 'courses:undo_enrollment' enrollment.course.slug %}" class="pure-button button-error">Cancelar</a>
							</div>
						</div>
						{% empty %}
							<aside class="pure-u-1">
								<p>Nenhum curso inscrito</p>
							</aside>
						{% endfor %}
					{% endif %}
				{% endwith %}
			{% endblock dashboard_content %}
		</div>
		</div>
	</div>
</div>
{% endblock content %}

simplemooc/accounts/templates/accounts/edit.html
{% extends "accounts/dashboard.html" %}

{% block breadcrumb %}
	{{ block.super }}
	<li><a href="">/</a></li>
	<li><a href="">Editar Conta</a></li>
{% endblock breadcrumb %}

{% block dashboard_content %}
<form class="pure-form pure-form-stacked" method="post">
	{% csrf_token %}
	{% if success %}
		<p>Os dados foram enviados com sucesso!</p>
	{% endif %}
	<fieldset>
		{{ form.non_field_errors }}
		{% for field in form %}
			<div class="pure-control-group">
				{{ field.label_tag}}
				{{ field }}
				{{ field.errors }}
			</div>
		{% endfor %}
		<div class="pure-controls">
			<button type="submit" class="pure-button pure-button-primary">Enviar</button>
		</div>
	</fieldset>
</form>
{% endblock dashboard_content %}

simplemooc/accounts/templates/accounts/edit_password.html
{% extends "accounts/dashboard.html" %}

{% block breadcrumb %}
	{{ block.super }}
	<li><a href="">/</a></li>
	<li><a href="">Editar senha</a></li>
{% endblock breadcrumb %}

{% block dashboard_content %}
<form class="pure-form pure-form-stacked" method="post">
	{% csrf_token %}
	{% if success %}
		<p>Sua senha foi alterada com sucesso com sucesso!</p>
	{% endif %}
	<fieldset>
		{{ form.non_field_errors }}
		{% for field in form %}
			<div class="pure-control-group">
				{{ field.label_tag}}
				{{ field }}
				{{ field.errors }}
			</div>
		{% endfor %}
		<div class="pure-controls">
			<button type="submit" class="pure-button pure-button-primary">Alterar senha</button>
		</div>
	</fieldset>
</form>
{% endblock dashboard_content %}

simplemooc/accounts/templates/accounts/login.html
{% extends "base.html" %}
{% block content %}
<div class="pure-g-r content-ribbon">
	<div class="pure-u-1">
		<h2>Informe seus dados de cadastro</h2>
		<form class="pure-form pure-form-stacked" method="post">
			{% csrf_token %}
			<fieldset>
				{{ form.non_field_errors }}

				{% for field in form %}
					<div class="pure-control-group">
						{{ field.label_tag }}
						{{ field }}
						{{ field.errors }}
					</div>
				{% endfor %}
				<div class="pure-controls">
					<button type="submit" class="pure-button pure-button-primary">Entrar</button>
				</div>
			</fieldset>
			<p>
				Não é cadastrado? <a href="{% url 'accounts:register' %}" title="">Cadastre-se</a> <br />
			</p>
			<p>
				Esqueceu a senha? <a href="" title="">Nova senha</a> <br />
			</p>
		</form>
	</div>
</div>
{% endblock content %}

simplemooc/accounts/templates/accounts/password_reset.html
{% extends "base.html" %}
{% block content %}
<div class="pure-g-r content-ribbon">
	<div class="pure-u-1">
		{% if success %}
			<p>Enviamos para você um email para que possa recuperar sua senha!</p>
		{% else %}
		<h2>Informe seu email:</h2>
		<form class="pure-form pure-form-stacked" method="post">
			{% csrf_token %}
			<fieldset>
				{{ form.non_field_errors }}

				{% for field in form %}
					<div class="pure-control-group">
						{{ field.label_tag }}
						{{ field }}
						{{ field.errors }}
					</div>
				{% endfor %}
				<div class="pure-controls">
					<button type="submit" class="pure-button pure-button-primary">Enviar email</button>
				</div>
			</fieldset>
		</form>
		{% endif %}
	</div>
</div>
{% endblock content %}

simplemooc/accounts/templates/accounts/password_reset_confirm.html
{% extends "base.html" %}
{% block content %}
<div class="pure-g-r content-ribbon">
	<div class="pure-u-1">
		{% if success %}
			<p>Sua nova senha foi criada com sucesso!</p>
		{% else %}
		<h2>Informe sua nova senha:</h2>
		<form class="pure-form pure-form-stacked" method="post">
			{% csrf_token %}
			<fieldset>
				{{ form.non_field_errors }}

				{% for field in form %}
					<div class="pure-control-group">
						{{ field.label_tag }}
						{{ field }}
						{{ field.errors }}
					</div>
				{% endfor %}
				<div class="pure-controls">
					<button type="submit" class="pure-button pure-button-primary">Criar nova senha</button>
				</div>
			</fieldset>
		</form>
		{% endif %}
	</div>
</div>
{% endblock content %}

simplemooc/accounts/templates/accounts/password_reset_mail.html
<p>Para criar uma nova senha, acesse o link abaixo.</p>
<a href="http://127.0.0.1:8000{% url 'accounts:password_reset_confirm' reset.key %}">Criar nova senha</a>

simplemooc/accounts/templates/accounts/register.html
{% extends "base.html" %}
{% block content %}
<div class="pure-g-r content-ribbon">
	<div class="pure-u-1">
		<h2>Informe seus dados:</h2>
		<form class="pure-form pure-form-stacked" method="post">
			{% csrf_token %}
			<fieldset>
				{{ form.non_field_errors }}

				{% for field in form %}
					<div class="pure-control-group">
						{{ field.label_tag }}
						{{ field }}
						{{ field.errors }}
					</div>
				{% endfor %}
				<div class="pure-controls">
					<button type="submit" class="pure-button pure-button-primary">Cadastrar</button>
				</div>
			</fieldset>
		</form>
	</div>
</div>
{% endblock content %}